LIBCMI_BASE_SRC := \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ama_ems.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ama_sce.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_cta_sce.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_dca_das.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ems_ama.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ne_ama.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ne_dca.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_olm_app.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_olm_sce.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_peer_peer.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_rmo_maint.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_sce_dca.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_serv_serv.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable_tra_trm.cc  \
@srcdir@/base/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ama_ems_linkdefs.cc \
@builddir@/src/cmi_ama_ems_v2000_linkdefs.cc \
@builddir@/src/cmi_ama_sce_linkdefs.cc \
@builddir@/src/cmi_ama_sce_v1000_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_appl_audit_linkdefs.cc \
@builddir@/src/cmi_ccl_ccl_linkdefs.cc \
@builddir@/src/cmi_ccl_pmo_linkdefs.cc \
@builddir@/src/cmi_cta_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5300_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_dca_das_linkdefs.cc \
@builddir@/src/cmi_dca_das_v4000_linkdefs.cc \
@builddir@/src/cmi_dca_sce_linkdefs.cc \
@builddir@/src/cmi_debug_debug_linkdefs.cc \
@builddir@/src/cmi_diagmgr_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ama_linkdefs.cc \
@builddir@/src/cmi_ems_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ems_mdtn_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_error_sce_linkdefs.cc \
@builddir@/src/cmi_mdtn_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ama_linkdefs.cc \
@builddir@/src/cmi_ne_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ne_dca_linkdefs.cc \
@builddir@/src/cmi_ne_dca_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_diagmgr_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_app_linkdefs.cc \
@builddir@/src/cmi_olm_app_v5700_linkdefs.cc \
@builddir@/src/cmi_olm_olm_linkdefs.cc \
@builddir@/src/cmi_olm_sce_linkdefs.cc \
@builddir@/src/cmi_olm_sce_v2000_linkdefs.cc \
@builddir@/src/cmi_peer_peer_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v511100_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5820_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5823_linkdefs.cc \
@builddir@/src/cmi_pmo_ccl_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_v5700_linkdefs.cc \
@builddir@/src/cmi_rmo_status_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_dca_linkdefs.cc \
@builddir@/src/cmi_sce_dca_v5740_linkdefs.cc \
@builddir@/src/cmi_sce_olm_linkdefs.cc \
@builddir@/src/cmi_sctp_sctp_linkdefs.cc \
@builddir@/src/cmi_serv_appl_linkdefs.cc \
@builddir@/src/cmi_serv_serv_linkdefs.cc \
@builddir@/src/cmi_serv_serv_v5500_linkdefs.cc \
@builddir@/src/cmi_tra_trm_linkdefs.cc \
@builddir@/src/cmi_tra_trm_v5700_linkdefs.cc \
@builddir@/src/cmi_trm_tra_linkdefs.cc \
@builddir@/src/cmi_ver_ver_linkdefs.cc \

LIBCMI_SNOOP_SRC1 := \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ama_ems.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ama_sce.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ase_cce.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_cce_ase.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ccs_rca.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_cta_sce.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_dca_das.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ems_ama.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ica_ss7.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ica_ss7maint.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ne_ama.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ne_dca.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_olm_app.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_olm_sce.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_peer_peer.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_rca_ccs.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_rmo_maint.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_sce_dca.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_serv_serv.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ss7_ica.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_ss7maint_ica.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable_tra_trm.cc  \
@srcdir@/snoop/src1/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ama_ems_linkdefs.cc \
@builddir@/src/cmi_ama_ems_v2000_linkdefs.cc \
@builddir@/src/cmi_ama_sce_linkdefs.cc \
@builddir@/src/cmi_ama_sce_v1000_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_appl_audit_linkdefs.cc \
@builddir@/src/cmi_ase_cce_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5741_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_ase_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v510100_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v59280_linkdefs.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_ccl_ccl_linkdefs.cc \
@builddir@/src/cmi_ccl_pmo_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v510100_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5925_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5929_linkdefs.cc \
@builddir@/src/cmi_cta_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5300_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_dca_das_linkdefs.cc \
@builddir@/src/cmi_dca_das_v4000_linkdefs.cc \
@builddir@/src/cmi_dca_sce_linkdefs.cc \
@builddir@/src/cmi_debug_debug_linkdefs.cc \
@builddir@/src/cmi_diagmgr_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ama_linkdefs.cc \
@builddir@/src/cmi_ems_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ems_mdtn_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_error_sce_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5925_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5929_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_mdtn_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ama_linkdefs.cc \
@builddir@/src/cmi_ne_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ne_dca_linkdefs.cc \
@builddir@/src/cmi_ne_dca_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_diagmgr_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_app_linkdefs.cc \
@builddir@/src/cmi_olm_app_v5700_linkdefs.cc \
@builddir@/src/cmi_olm_olm_linkdefs.cc \
@builddir@/src/cmi_olm_sce_linkdefs.cc \
@builddir@/src/cmi_olm_sce_v2000_linkdefs.cc \
@builddir@/src/cmi_peer_peer_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v511100_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5820_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5823_linkdefs.cc \
@builddir@/src/cmi_pmo_ccl_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v510100_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5925_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5929_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_v5700_linkdefs.cc \
@builddir@/src/cmi_rmo_status_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_dca_linkdefs.cc \
@builddir@/src/cmi_sce_dca_v5740_linkdefs.cc \
@builddir@/src/cmi_sce_olm_linkdefs.cc \
@builddir@/src/cmi_sctp_sctp_linkdefs.cc \
@builddir@/src/cmi_serv_appl_linkdefs.cc \
@builddir@/src/cmi_serv_serv_linkdefs.cc \
@builddir@/src/cmi_serv_serv_v5500_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v510100_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5925_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5929_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5700_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5810_linkdefs.cc \
@builddir@/src/cmi_tra_trm_linkdefs.cc \
@builddir@/src/cmi_tra_trm_v5700_linkdefs.cc \
@builddir@/src/cmi_trm_tra_linkdefs.cc \
@builddir@/src/cmi_ver_ver_linkdefs.cc \

LIBCMI_SERVICES_SRC := \
@srcdir@/services/src/cmi_cmi_versions_alloctable_ase_cce.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_cce_ase.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_inap_tcap.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_lis_ne.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_msc_hlr.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_msc_msc.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_ne_lis.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_ne_pse.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_ne_ras.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_pse_ne.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_see_cec.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable_tcap_inap.cc  \
@srcdir@/services/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ain_tcap_linkdefs.cc \
@builddir@/src/cmi_ase_cce_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5741_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_ase_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v510100_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v59280_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5820_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5930_linkdefs.cc \
@builddir@/src/cmi_lis_ne_linkdefs.cc \
@builddir@/src/cmi_lis_ne_v5600_linkdefs.cc \
@builddir@/src/cmi_msc_hlr_linkdefs.cc \
@builddir@/src/cmi_msc_hlr_v5820_linkdefs.cc \
@builddir@/src/cmi_msc_msc_linkdefs.cc \
@builddir@/src/cmi_msc_msc_v5820_linkdefs.cc \
@builddir@/src/cmi_ne_lis_linkdefs.cc \
@builddir@/src/cmi_ne_lis_v5600_linkdefs.cc \
@builddir@/src/cmi_ne_pse_linkdefs.cc \
@builddir@/src/cmi_ne_pse_v59290_linkdefs.cc \
@builddir@/src/cmi_ne_ras_linkdefs.cc \
@builddir@/src/cmi_ne_ras_v5600_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_pse_ne_linkdefs.cc \
@builddir@/src/cmi_pse_ne_v59290_linkdefs.cc \
@builddir@/src/cmi_ras_ne_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_see_cec_linkdefs.cc \
@builddir@/src/cmi_see_cec_v5100_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \
@builddir@/src/cmi_see_see_linkdefs.cc \
@builddir@/src/cmi_see_tpcc_linkdefs.cc \
@builddir@/src/cmi_tcap_ain_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_v5929_linkdefs.cc \
@builddir@/src/cmi_tpcc_see_linkdefs.cc \

LIBCMI_SCE_SRC := \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ama_sce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_cce_pfm.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_cta_sce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ems_ibcf.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ems_lis.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ems_mse.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ems_racs.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_olm_sce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_rde_sce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/sce/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ama_sce_linkdefs.cc \
@builddir@/src/cmi_ama_sce_v1000_linkdefs.cc \
@builddir@/src/cmi_cce_pfm_linkdefs.cc \
@builddir@/src/cmi_cce_pfm_v2000_linkdefs.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_cdr_sce_linkdefs.cc \
@builddir@/src/cmi_cec_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5300_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_debug_debug_linkdefs.cc \
@builddir@/src/cmi_ems_dca_linkdefs.cc \
@builddir@/src/cmi_ems_dse_linkdefs.cc \
@builddir@/src/cmi_ems_ibcf_linkdefs.cc \
@builddir@/src/cmi_ems_ibcf_v5740_linkdefs.cc \
@builddir@/src/cmi_ems_lis_linkdefs.cc \
@builddir@/src/cmi_ems_lis_v5600_linkdefs.cc \
@builddir@/src/cmi_ems_lsg_linkdefs.cc \
@builddir@/src/cmi_ems_mse_linkdefs.cc \
@builddir@/src/cmi_ems_mse_v5740_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_racs_linkdefs.cc \
@builddir@/src/cmi_ems_racs_v5700_linkdefs.cc \
@builddir@/src/cmi_ems_racs_v5800_linkdefs.cc \
@builddir@/src/cmi_error_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_sce_linkdefs.cc \
@builddir@/src/cmi_olm_sce_v2000_linkdefs.cc \
@builddir@/src/cmi_rde_sce_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5200_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_sce_cdr_linkdefs.cc \
@builddir@/src/cmi_sce_cec_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_sce_olm_linkdefs.cc \
@builddir@/src/cmi_sce_rde_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_sce_ss7_linkdefs.cc \
@builddir@/src/cmi_sce_ss7a_linkdefs.cc \
@builddir@/src/cmi_sce_ss7a_linkdefs.cc \
@builddir@/src/cmi_sce_tcap_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \
@builddir@/src/cmi_see_tpcc_linkdefs.cc \
@builddir@/src/cmi_ss7_sce_linkdefs.cc \
@builddir@/src/cmi_ss7a_sce_linkdefs.cc \
@builddir@/src/cmi_tcap_sce_linkdefs.cc \
@builddir@/src/cmi_tpcc_see_linkdefs.cc \

LIBCMI_RE_SRC := \
@srcdir@/re/src/cmi_cmi_versions_alloctable_ne_pse.cc  \
@srcdir@/re/src/cmi_cmi_versions_alloctable_pse_ne.cc  \
@srcdir@/re/src/cmi_cmi_versions_alloctable_rde_sce.cc  \
@srcdir@/re/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_dca_pse_linkdefs.cc \
@builddir@/src/cmi_dse_ne_linkdefs.cc \
@builddir@/src/cmi_ne_dse_linkdefs.cc \
@builddir@/src/cmi_ne_pse_linkdefs.cc \
@builddir@/src/cmi_ne_pse_v59290_linkdefs.cc \
@builddir@/src/cmi_pse_ne_linkdefs.cc \
@builddir@/src/cmi_pse_ne_v59290_linkdefs.cc \
@builddir@/src/cmi_rde_sce_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5200_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_rde_tcap_linkdefs.cc \
@builddir@/src/cmi_sce_rde_linkdefs.cc \
@builddir@/src/cmi_tcap_rde_linkdefs.cc \

LIBCMI_RE_REA_SRC := \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_ne_pse.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_pse_ne.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_rde_sce.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/re/rea_src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_pse_linkdefs.cc \
@builddir@/src/cmi_ne_pse_v59290_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_pse_ne_linkdefs.cc \
@builddir@/src/cmi_pse_ne_v59290_linkdefs.cc \
@builddir@/src/cmi_rde_sce_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5200_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_sce_rde_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \

LIBCMI_NEA_SRC := \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/nea/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_nea_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_nea_ne_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \

LIBCMI_MRCE_SRC := \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_af_spdf.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_ase_cce.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_cce_ase.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_ccs_rca.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_ems_racs.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_rca_ccs.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable_spdf_af.cc  \
@srcdir@/mrce/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_af_spdf_linkdefs.cc \
@builddir@/src/cmi_af_spdf_v5700_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_ase_cce_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5741_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_ase_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v510100_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v59280_linkdefs.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v510100_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5925_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5929_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_racs_linkdefs.cc \
@builddir@/src/cmi_ems_racs_v5700_linkdefs.cc \
@builddir@/src/cmi_ems_racs_v5800_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_racs_ems_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v510100_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5925_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5929_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_spdf_af_linkdefs.cc \
@builddir@/src/cmi_spdf_af_v5700_linkdefs.cc \

LIBCMI_LSG_SRC := \
@srcdir@/lsg/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/lsg/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/lsg/src/cmi_cmi_versions_alloctable_inap_tcap.cc  \
@srcdir@/lsg/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/lsg/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/lsg/src/cmi_cmi_versions_alloctable_tcap_inap.cc  \
@srcdir@/lsg/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ems_lsg_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5820_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5930_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_v5929_linkdefs.cc \

LIBCMI_LIDAP_SRC := \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_ems_lis.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_licp_lidap.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_lis_ne.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_ne_lis.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/lidap/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ems_lis_linkdefs.cc \
@builddir@/src/cmi_ems_lis_v5600_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_licp_lidap_linkdefs.cc \
@builddir@/src/cmi_licp_lidap_v5800_linkdefs.cc \
@builddir@/src/cmi_lidap_licp_linkdefs.cc \
@builddir@/src/cmi_lis_ne_linkdefs.cc \
@builddir@/src/cmi_lis_ne_v5600_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_lis_linkdefs.cc \
@builddir@/src/cmi_ne_lis_v5600_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \

LIBCMI_INAP_SRC := \
@srcdir@/inap/src/cmi_cmi_versions_alloctable_inap_tcap.cc  \
@srcdir@/inap/src/cmi_cmi_versions_alloctable_tcap_inap.cc  \
@srcdir@/inap/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_inap_tcap_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5820_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5930_linkdefs.cc \
@builddir@/src/cmi_sce_tcap_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_v5929_linkdefs.cc \
@builddir@/src/cmi_tcap_sce_linkdefs.cc \

LIBCMI_ICE_SRC := \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_af_spdf.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_ase_cce.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_cce_ase.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_ccs_rca.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_ica_ss7.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_ne_ras.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_peer_peer.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_rca_ccs.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable_spdf_af.cc  \
@srcdir@/ice/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_af_spdf_linkdefs.cc \
@builddir@/src/cmi_af_spdf_v5700_linkdefs.cc \
@builddir@/src/cmi_ase_cce_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5741_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_ase_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v510100_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v59280_linkdefs.cc \
@builddir@/src/cmi_cce_cce_linkdefs.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_ccl_pmo_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v510100_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5925_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5929_linkdefs.cc \
@builddir@/src/cmi_clientdebug_clientdebug_linkdefs.cc \
@builddir@/src/cmi_clientdebug_server_linkdefs.cc \
@builddir@/src/cmi_dcs_ne_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5925_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5929_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_ne_dcs_linkdefs.cc \
@builddir@/src/cmi_ne_ras_linkdefs.cc \
@builddir@/src/cmi_ne_ras_v5600_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_ospa_ospc_linkdefs.cc \
@builddir@/src/cmi_ospc_ospa_linkdefs.cc \
@builddir@/src/cmi_peer_peer_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v511100_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5820_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5823_linkdefs.cc \
@builddir@/src/cmi_ras_ne_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v510100_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5925_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5929_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_server_clientdebug_linkdefs.cc \
@builddir@/src/cmi_spdf_af_linkdefs.cc \
@builddir@/src/cmi_spdf_af_v5700_linkdefs.cc \

LIBCMI_IBCF_SRC := \
@srcdir@/ibcf/src/cmi_cmi_versions_alloctable_ems_ibcf.cc  \
@srcdir@/ibcf/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/ibcf/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/ibcf/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/ibcf/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/ibcf/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_dcl_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ibcf_linkdefs.cc \
@builddir@/src/cmi_ems_ibcf_v5740_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_dcl_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_nea_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_nea_ne_linkdefs.cc \

LIBCMI_ERS_SRC := \
@srcdir@/ers/src/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/ers/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/ers/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/ers/src/cmi_cmi_versions_alloctable_nce_cec.cc  \
@srcdir@/ers/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/ers/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/ers/src/cmi_cmi_versions_alloctable_see_cec.cc  \
@srcdir@/ers/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_ema_ers_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ers_ema_linkdefs.cc \
@builddir@/src/cmi_nce_cec_linkdefs.cc \
@builddir@/src/cmi_nce_cec_v5600_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_see_cec_linkdefs.cc \
@builddir@/src/cmi_see_cec_v5100_linkdefs.cc \

LIBCMI_DSE_SRC := \
@srcdir@/dse/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/dse/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/dse/src/cmi_cmi_versions_alloctable_inap_tcap.cc  \
@srcdir@/dse/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/dse/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/dse/src/cmi_cmi_versions_alloctable_tcap_inap.cc  \
@srcdir@/dse/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_dse_dsesync_linkdefs.cc \
@builddir@/src/cmi_dse_ne_linkdefs.cc \
@builddir@/src/cmi_dsesync_dse_linkdefs.cc \
@builddir@/src/cmi_ems_dse_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5820_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5930_linkdefs.cc \
@builddir@/src/cmi_ne_dse_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_v5929_linkdefs.cc \

LIBCMI_DCS_SRC := \
@srcdir@/dcs/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/dcs/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/dcs/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/dcs/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/dcs/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_dcs_dcs_linkdefs.cc \
@builddir@/src/cmi_dcs_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_dcs_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \

LIBCMI_DCA_SRC := \
@srcdir@/dca/src/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/dca/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/dca/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/dca/src/cmi_cmi_versions_alloctable_nce_cec.cc  \
@srcdir@/dca/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/dca/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/dca/src/cmi_cmi_versions_alloctable_rtdca_rtdas.cc  \
@srcdir@/dca/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_dca_pse_linkdefs.cc \
@builddir@/src/cmi_ema_ers_linkdefs.cc \
@builddir@/src/cmi_ems_dca_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ers_ema_linkdefs.cc \
@builddir@/src/cmi_nce_cec_linkdefs.cc \
@builddir@/src/cmi_nce_cec_v5600_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_rtdas_rtdca_linkdefs.cc \
@builddir@/src/cmi_rtdca_rtdas_linkdefs.cc \
@builddir@/src/cmi_rtdca_rtdas_v5900_linkdefs.cc \

LIBCMI_DAS_SRC := \
@srcdir@/das/src/cmi_cmi_versions_alloctable_rtdca_rtdas.cc  \
@srcdir@/das/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_rtdas_rtdca_linkdefs.cc \
@builddir@/src/cmi_rtdca_rtdas_linkdefs.cc \
@builddir@/src/cmi_rtdca_rtdas_v5900_linkdefs.cc \

LIBCMI_CGW_SRC := \
@srcdir@/cgw/src/cmi_cmi_versions_alloctable_ems_cgw.cc  \
@srcdir@/cgw/src/cmi_cmi_versions_alloctable_ne_pse.cc  \
@srcdir@/cgw/src/cmi_cmi_versions_alloctable_pse_ne.cc  \
@srcdir@/cgw/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cgw_ems_linkdefs.cc \
@builddir@/src/cmi_ems_cgw_linkdefs.cc \
@builddir@/src/cmi_ems_cgw_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_pse_linkdefs.cc \
@builddir@/src/cmi_ne_pse_v59290_linkdefs.cc \
@builddir@/src/cmi_pse_ne_linkdefs.cc \
@builddir@/src/cmi_pse_ne_v59290_linkdefs.cc \

LIBCMI_CEC_SRC := \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_nce_cec.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_see_cec.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/cec/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_cdr_sce_linkdefs.cc \
@builddir@/src/cmi_cec_cec_linkdefs.cc \
@builddir@/src/cmi_cec_sce_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_nce_cec_linkdefs.cc \
@builddir@/src/cmi_nce_cec_v5600_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_sce_cdr_linkdefs.cc \
@builddir@/src/cmi_sce_cec_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_see_cec_linkdefs.cc \
@builddir@/src/cmi_see_cec_v5100_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \

LIBCMI_CEC_CECA_SRC := \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/cec/ceca_src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_cec_cec_linkdefs.cc \
@builddir@/src/cmi_cec_sce_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_sce_cec_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \

LIBCMI_CEC_CDRA_SRC := \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/cec/cdra_src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_cdr_sce_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_sce_cdr_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \

LIBCMI_CCS_SRC := \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_af_spdf.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_ase_cce.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_cce_ase.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_ccs_rca.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_ica_ss7.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_ica_ss7maint.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_rca_ccs.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_spdf_af.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_ss7_ica.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable_ss7maint_ica.cc  \
@srcdir@/ccs/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_af_spdf_linkdefs.cc \
@builddir@/src/cmi_af_spdf_v5700_linkdefs.cc \
@builddir@/src/cmi_app_sm_linkdefs.cc \
@builddir@/src/cmi_ase_cce_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5741_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_ase_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v510100_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v59280_linkdefs.cc \
@builddir@/src/cmi_cce_cce_linkdefs.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v510100_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5925_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5929_linkdefs.cc \
@builddir@/src/cmi_clientdebug_clientdebug_linkdefs.cc \
@builddir@/src/cmi_clientdebug_server_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5925_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5929_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_olm_ss7_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v510100_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5925_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5929_linkdefs.cc \
@builddir@/src/cmi_rudp_rudp_linkdefs.cc \
@builddir@/src/cmi_rudp_sm_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_server_clientdebug_linkdefs.cc \
@builddir@/src/cmi_sm_app_linkdefs.cc \
@builddir@/src/cmi_sm_rudp_linkdefs.cc \
@builddir@/src/cmi_spdf_af_linkdefs.cc \
@builddir@/src/cmi_spdf_af_v5700_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v510100_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5925_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5929_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5700_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5810_linkdefs.cc \

LIBCMI_CCS_CCPA_SRC := \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_ice_sce.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_sce_ice.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_sce_see.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable_see_sce.cc  \
@srcdir@/ccs/ccpa_src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_cce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ice_sce_linkdefs.cc \
@builddir@/src/cmi_ice_sce_v5500_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_sce_ice_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_ice_v5900_linkdefs.cc \
@builddir@/src/cmi_sce_see_linkdefs.cc \
@builddir@/src/cmi_sce_see_v5820_linkdefs.cc \
@builddir@/src/cmi_see_sce_linkdefs.cc \
@builddir@/src/cmi_see_sce_v5400_linkdefs.cc \

LIBCMI_BGC_SRC := \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_af_spdf.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_ems_racs.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_ne_dca.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_rmo_maint.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_sce_dca.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable_spdf_af.cc  \
@srcdir@/bgc/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_af_spdf_linkdefs.cc \
@builddir@/src/cmi_af_spdf_v5700_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_racs_linkdefs.cc \
@builddir@/src/cmi_ems_racs_v5700_linkdefs.cc \
@builddir@/src/cmi_ems_racs_v5800_linkdefs.cc \
@builddir@/src/cmi_ne_dca_linkdefs.cc \
@builddir@/src/cmi_ne_dca_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_racs_ems_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_v5700_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_dca_linkdefs.cc \
@builddir@/src/cmi_sce_dca_v5740_linkdefs.cc \
@builddir@/src/cmi_spdf_af_linkdefs.cc \
@builddir@/src/cmi_spdf_af_v5700_linkdefs.cc \

LIBCMI_TRACER_SRC := \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ama_sce.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ase_cce.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_cce_ase.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_cce_cec.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_cce_pfm.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_cce_sce.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ccs_rca.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_cta_sce.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_dca_das.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ems_ama.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ems_mse.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ica_ss7.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ica_ss7maint.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ne_pse.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_olm_app.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_olm_sce.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_peer_peer.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_pse_ne.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_rca_ccs.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_rde_sce.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_rmo_maint.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_sce_dca.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ss7_ica.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable_ss7maint_ica.cc  \
@srcdir@/tracer/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ama_sce_linkdefs.cc \
@builddir@/src/cmi_ama_sce_v1000_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_app_sm_linkdefs.cc \
@builddir@/src/cmi_ase_cce_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5741_linkdefs.cc \
@builddir@/src/cmi_ase_cce_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_ase_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v510100_linkdefs.cc \
@builddir@/src/cmi_cce_ase_v59280_linkdefs.cc \
@builddir@/src/cmi_cce_cce_linkdefs.cc \
@builddir@/src/cmi_cce_cec_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5820_linkdefs.cc \
@builddir@/src/cmi_cce_cec_v5900_linkdefs.cc \
@builddir@/src/cmi_cce_pfm_linkdefs.cc \
@builddir@/src/cmi_cce_pfm_v2000_linkdefs.cc \
@builddir@/src/cmi_cce_sce_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5700_linkdefs.cc \
@builddir@/src/cmi_cce_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v510100_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5925_linkdefs.cc \
@builddir@/src/cmi_ccs_rca_v5929_linkdefs.cc \
@builddir@/src/cmi_cdr_sce_linkdefs.cc \
@builddir@/src/cmi_cec_cec_linkdefs.cc \
@builddir@/src/cmi_cec_sce_linkdefs.cc \
@builddir@/src/cmi_clientdebug_clientdebug_linkdefs.cc \
@builddir@/src/cmi_clientdebug_server_linkdefs.cc \
@builddir@/src/cmi_cta_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5300_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_dca_das_linkdefs.cc \
@builddir@/src/cmi_dca_das_v4000_linkdefs.cc \
@builddir@/src/cmi_dca_sce_linkdefs.cc \
@builddir@/src/cmi_ems_ama_linkdefs.cc \
@builddir@/src/cmi_ems_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ems_mse_linkdefs.cc \
@builddir@/src/cmi_ems_mse_v5740_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_error_sce_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5925_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5929_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_pse_linkdefs.cc \
@builddir@/src/cmi_ne_pse_v59290_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_app_linkdefs.cc \
@builddir@/src/cmi_olm_app_v5700_linkdefs.cc \
@builddir@/src/cmi_olm_sce_linkdefs.cc \
@builddir@/src/cmi_olm_sce_v2000_linkdefs.cc \
@builddir@/src/cmi_olm_ss7_linkdefs.cc \
@builddir@/src/cmi_peer_peer_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v511100_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5820_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5823_linkdefs.cc \
@builddir@/src/cmi_pse_ne_linkdefs.cc \
@builddir@/src/cmi_pse_ne_v59290_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v510100_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5925_linkdefs.cc \
@builddir@/src/cmi_rca_ccs_v5929_linkdefs.cc \
@builddir@/src/cmi_rde_sce_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5200_linkdefs.cc \
@builddir@/src/cmi_rde_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_rde_tcap_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_v5700_linkdefs.cc \
@builddir@/src/cmi_rmo_status_linkdefs.cc \
@builddir@/src/cmi_rudp_rudp_linkdefs.cc \
@builddir@/src/cmi_rudp_sm_linkdefs.cc \
@builddir@/src/cmi_sce_cdr_linkdefs.cc \
@builddir@/src/cmi_sce_cec_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_dca_linkdefs.cc \
@builddir@/src/cmi_sce_dca_v5740_linkdefs.cc \
@builddir@/src/cmi_sce_olm_linkdefs.cc \
@builddir@/src/cmi_sce_rde_linkdefs.cc \
@builddir@/src/cmi_sce_ss7_linkdefs.cc \
@builddir@/src/cmi_sce_ss7a_linkdefs.cc \
@builddir@/src/cmi_sce_ss7a_linkdefs.cc \
@builddir@/src/cmi_sce_tcap_linkdefs.cc \
@builddir@/src/cmi_server_clientdebug_linkdefs.cc \
@builddir@/src/cmi_sm_app_linkdefs.cc \
@builddir@/src/cmi_sm_rudp_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v510100_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5925_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5929_linkdefs.cc \
@builddir@/src/cmi_ss7_sce_linkdefs.cc \
@builddir@/src/cmi_ss7a_sce_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5700_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5810_linkdefs.cc \
@builddir@/src/cmi_ss7mo_ss7mo_linkdefs.cc \
@builddir@/src/cmi_sse_sse_linkdefs.cc \
@builddir@/src/cmi_tcap_rde_linkdefs.cc \
@builddir@/src/cmi_tcap_sce_linkdefs.cc \
@builddir@/src/cmi_ver_ver_linkdefs.cc \

LIBCMI_TEST_SCTP_TEST_SRC := \
@srcdir@/test/sctp_test/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_cce_cce_linkdefs.cc \
@builddir@/src/cmi_test_test_linkdefs.cc \
@builddir@/src/cmi_test1_test2_linkdefs.cc \
@builddir@/src/cmi_test2_test3_linkdefs.cc \
@builddir@/src/cmi_test3_test1_linkdefs.cc \

LIBCMI_TCAPSE_SRC := \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_ems_mse.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_inap_tcap.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_m3ua_l4app.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_msc_hlr.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_msc_msc.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable_tcap_inap.cc  \
@srcdir@/tcapse/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_ems_mse_linkdefs.cc \
@builddir@/src/cmi_ems_mse_v5740_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5820_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5930_linkdefs.cc \
@builddir@/src/cmi_l4app_m3ua_linkdefs.cc \
@builddir@/src/cmi_m3ua_l4app_linkdefs.cc \
@builddir@/src/cmi_m3ua_l4app_v5800_linkdefs.cc \
@builddir@/src/cmi_msc_hlr_linkdefs.cc \
@builddir@/src/cmi_msc_hlr_v5820_linkdefs.cc \
@builddir@/src/cmi_msc_msc_linkdefs.cc \
@builddir@/src/cmi_msc_msc_v5820_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_v5929_linkdefs.cc \

LIBCMI_STANDALONE_SRC := \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ama_ems.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ama_sce.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_cta_sce.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_dca_das.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ems_ama.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ne_ama.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ne_dca.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_olm_app.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_olm_sce.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_peer_peer.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_rmo_maint.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_sce_dca.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_serv_serv.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable_tra_trm.cc  \
@srcdir@/standalone/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ama_ems_linkdefs.cc \
@builddir@/src/cmi_ama_ems_v2000_linkdefs.cc \
@builddir@/src/cmi_ama_sce_linkdefs.cc \
@builddir@/src/cmi_ama_sce_v1000_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_appl_audit_linkdefs.cc \
@builddir@/src/cmi_ccl_ccl_linkdefs.cc \
@builddir@/src/cmi_ccl_pmo_linkdefs.cc \
@builddir@/src/cmi_cta_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5300_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_dca_das_linkdefs.cc \
@builddir@/src/cmi_dca_das_v4000_linkdefs.cc \
@builddir@/src/cmi_dca_sce_linkdefs.cc \
@builddir@/src/cmi_debug_debug_linkdefs.cc \
@builddir@/src/cmi_diagmgr_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ama_linkdefs.cc \
@builddir@/src/cmi_ems_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ems_mdtn_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_error_sce_linkdefs.cc \
@builddir@/src/cmi_mdtn_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ama_linkdefs.cc \
@builddir@/src/cmi_ne_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ne_dca_linkdefs.cc \
@builddir@/src/cmi_ne_dca_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_diagmgr_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_app_linkdefs.cc \
@builddir@/src/cmi_olm_app_v5700_linkdefs.cc \
@builddir@/src/cmi_olm_olm_linkdefs.cc \
@builddir@/src/cmi_olm_sce_linkdefs.cc \
@builddir@/src/cmi_olm_sce_v2000_linkdefs.cc \
@builddir@/src/cmi_peer_peer_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v511100_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5820_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5823_linkdefs.cc \
@builddir@/src/cmi_pmo_ccl_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_v5700_linkdefs.cc \
@builddir@/src/cmi_rmo_status_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_dca_linkdefs.cc \
@builddir@/src/cmi_sce_dca_v5740_linkdefs.cc \
@builddir@/src/cmi_sce_olm_linkdefs.cc \
@builddir@/src/cmi_sctp_sctp_linkdefs.cc \
@builddir@/src/cmi_serv_appl_linkdefs.cc \
@builddir@/src/cmi_serv_serv_linkdefs.cc \
@builddir@/src/cmi_serv_serv_v5500_linkdefs.cc \
@builddir@/src/cmi_tra_trm_linkdefs.cc \
@builddir@/src/cmi_tra_trm_v5700_linkdefs.cc \
@builddir@/src/cmi_trm_tra_linkdefs.cc \
@builddir@/src/cmi_ver_ver_linkdefs.cc \

LIBCMI_SSE_SRC := \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ems_mse.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ica_ss7.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ica_ss7maint.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_m3ua_l4app.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ss7_ica.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable_ss7maint_ica.cc  \
@srcdir@/sse/src/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_ems_mse_linkdefs.cc \
@builddir@/src/cmi_ems_mse_v5740_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5925_linkdefs.cc \
@builddir@/src/cmi_ica_ss7_v5929_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_ica_ss7maint_v5700_linkdefs.cc \
@builddir@/src/cmi_l4app_m3ua_linkdefs.cc \
@builddir@/src/cmi_m3ua_l4app_linkdefs.cc \
@builddir@/src/cmi_m3ua_l4app_v5800_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_ss7_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v510100_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5925_linkdefs.cc \
@builddir@/src/cmi_ss7_ica_v5929_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5700_linkdefs.cc \
@builddir@/src/cmi_ss7maint_ica_v5810_linkdefs.cc \
@builddir@/src/cmi_sse_sse_linkdefs.cc \

LIBCMI_SNOOP_SRC2 := \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ama_ems.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ama_sce.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_cta_sce.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_dca_das.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ems_ama.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_inap_tcap.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ne_ama.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ne_dca.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_ne_pse.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_olm_app.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_olm_sce.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_peer_peer.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_pse_ne.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_rmo_maint.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_sce_dca.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_serv_serv.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_tcap_inap.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable_tra_trm.cc  \
@srcdir@/snoop/src2/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ama_ems_linkdefs.cc \
@builddir@/src/cmi_ama_ems_v2000_linkdefs.cc \
@builddir@/src/cmi_ama_sce_linkdefs.cc \
@builddir@/src/cmi_ama_sce_v1000_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_appl_audit_linkdefs.cc \
@builddir@/src/cmi_ccl_ccl_linkdefs.cc \
@builddir@/src/cmi_ccl_pmo_linkdefs.cc \
@builddir@/src/cmi_cta_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5300_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_dca_das_linkdefs.cc \
@builddir@/src/cmi_dca_das_v4000_linkdefs.cc \
@builddir@/src/cmi_dca_sce_linkdefs.cc \
@builddir@/src/cmi_debug_debug_linkdefs.cc \
@builddir@/src/cmi_diagmgr_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ama_linkdefs.cc \
@builddir@/src/cmi_ems_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ems_mdtn_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_error_sce_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5820_linkdefs.cc \
@builddir@/src/cmi_inap_tcap_v5930_linkdefs.cc \
@builddir@/src/cmi_mdtn_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ama_linkdefs.cc \
@builddir@/src/cmi_ne_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ne_dca_linkdefs.cc \
@builddir@/src/cmi_ne_dca_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_diagmgr_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_ne_pse_linkdefs.cc \
@builddir@/src/cmi_ne_pse_v59290_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_app_linkdefs.cc \
@builddir@/src/cmi_olm_app_v5700_linkdefs.cc \
@builddir@/src/cmi_olm_olm_linkdefs.cc \
@builddir@/src/cmi_olm_sce_linkdefs.cc \
@builddir@/src/cmi_olm_sce_v2000_linkdefs.cc \
@builddir@/src/cmi_peer_peer_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v511100_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5820_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5823_linkdefs.cc \
@builddir@/src/cmi_pmo_ccl_linkdefs.cc \
@builddir@/src/cmi_pse_ne_linkdefs.cc \
@builddir@/src/cmi_pse_ne_v59290_linkdefs.cc \
@builddir@/src/cmi_rde_tcap_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_v5700_linkdefs.cc \
@builddir@/src/cmi_rmo_status_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_dca_linkdefs.cc \
@builddir@/src/cmi_sce_dca_v5740_linkdefs.cc \
@builddir@/src/cmi_sce_olm_linkdefs.cc \
@builddir@/src/cmi_sctp_sctp_linkdefs.cc \
@builddir@/src/cmi_serv_appl_linkdefs.cc \
@builddir@/src/cmi_serv_serv_linkdefs.cc \
@builddir@/src/cmi_serv_serv_v5500_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_linkdefs.cc \
@builddir@/src/cmi_tcap_inap_v5929_linkdefs.cc \
@builddir@/src/cmi_tcap_rde_linkdefs.cc \
@builddir@/src/cmi_tra_trm_linkdefs.cc \
@builddir@/src/cmi_tra_trm_v5700_linkdefs.cc \
@builddir@/src/cmi_trm_tra_linkdefs.cc \
@builddir@/src/cmi_ver_ver_linkdefs.cc \

LIBCMI_SNOOP_SRC3 := \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ama_ems.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ama_sce.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_cta_sce.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_dca_das.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ems_ama.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ems_ne.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ems_nea.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ne_ama.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ne_dca.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_ne_ems.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_nea_ems.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_olm_app.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_olm_sce.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_peer_peer.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_rmo_maint.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_sce_cce.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_sce_cta.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_sce_dca.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_serv_serv.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable_tra_trm.cc  \
@srcdir@/snoop/src3/cmi_cmi_versions_alloctable.cc \
@builddir@/src/cmi_ama_ems_linkdefs.cc \
@builddir@/src/cmi_ama_ems_v2000_linkdefs.cc \
@builddir@/src/cmi_ama_sce_linkdefs.cc \
@builddir@/src/cmi_ama_sce_v1000_linkdefs.cc \
@builddir@/src/cmi_app_mo_linkdefs.cc \
@builddir@/src/cmi_appl_audit_linkdefs.cc \
@builddir@/src/cmi_ccl_ccl_linkdefs.cc \
@builddir@/src/cmi_ccl_pmo_linkdefs.cc \
@builddir@/src/cmi_cta_sce_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5300_linkdefs.cc \
@builddir@/src/cmi_cta_sce_v5800_linkdefs.cc \
@builddir@/src/cmi_dca_das_linkdefs.cc \
@builddir@/src/cmi_dca_das_v4000_linkdefs.cc \
@builddir@/src/cmi_dca_sce_linkdefs.cc \
@builddir@/src/cmi_debug_debug_linkdefs.cc \
@builddir@/src/cmi_diagmgr_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ama_linkdefs.cc \
@builddir@/src/cmi_ems_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ems_mdtn_linkdefs.cc \
@builddir@/src/cmi_ems_ne_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_ne_v6100_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v5000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_ems_nea_v6000_linkdefs.cc \
@builddir@/src/cmi_error_sce_linkdefs.cc \
@builddir@/src/cmi_mdtn_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ama_linkdefs.cc \
@builddir@/src/cmi_ne_ama_v2000_linkdefs.cc \
@builddir@/src/cmi_ne_dca_linkdefs.cc \
@builddir@/src/cmi_ne_dca_v5700_linkdefs.cc \
@builddir@/src/cmi_ne_diagmgr_linkdefs.cc \
@builddir@/src/cmi_ne_ems_linkdefs.cc \
@builddir@/src/cmi_ne_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v5000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6000_linkdefs.cc \
@builddir@/src/cmi_nea_ems_v6010_linkdefs.cc \
@builddir@/src/cmi_olm_app_linkdefs.cc \
@builddir@/src/cmi_olm_app_v5700_linkdefs.cc \
@builddir@/src/cmi_olm_olm_linkdefs.cc \
@builddir@/src/cmi_olm_sce_linkdefs.cc \
@builddir@/src/cmi_olm_sce_v2000_linkdefs.cc \
@builddir@/src/cmi_peer_peer_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v511100_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5820_linkdefs.cc \
@builddir@/src/cmi_peer_peer_v5823_linkdefs.cc \
@builddir@/src/cmi_pmo_ccl_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_linkdefs.cc \
@builddir@/src/cmi_rmo_maint_v5700_linkdefs.cc \
@builddir@/src/cmi_rmo_status_linkdefs.cc \
@builddir@/src/cmi_sce_cce_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510100_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v510210_linkdefs.cc \
@builddir@/src/cmi_sce_cce_v59285_linkdefs.cc \
@builddir@/src/cmi_sce_cta_linkdefs.cc \
@builddir@/src/cmi_sce_cta_v5500_linkdefs.cc \
@builddir@/src/cmi_sce_dca_linkdefs.cc \
@builddir@/src/cmi_sce_dca_v5740_linkdefs.cc \
@builddir@/src/cmi_sce_olm_linkdefs.cc \
@builddir@/src/cmi_sctp_sctp_linkdefs.cc \
@builddir@/src/cmi_serv_appl_linkdefs.cc \
@builddir@/src/cmi_serv_serv_linkdefs.cc \
@builddir@/src/cmi_serv_serv_v5500_linkdefs.cc \
@builddir@/src/cmi_tra_trm_linkdefs.cc \
@builddir@/src/cmi_tra_trm_v5700_linkdefs.cc \
@builddir@/src/cmi_trm_tra_linkdefs.cc \
@builddir@/src/cmi_ver_ver_linkdefs.cc \

